# Generated by Django 5.1.7 on 2025-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='skills',
        ),
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(to='timesheetApp.skill'),
        ),
    ]
