# Generated by Django 5.1.7 on 2025-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetApp', '0002_skill_remove_team_skills_team_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assumption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
