# Generated by Django 5.1.7 on 2025-03-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetApp', '0003_team_updated_at_alter_task_assumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='teams',
            new_name='team',
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_entry', models.DateField()),
                ('description', models.TextField()),
                ('time_entry', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetApp.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetApp.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetApp.task')),
            ],
        ),
    ]
